### PR TITLE
Fix for issue #108, add a flag to manage guest hosts file.

### PR DESCRIPTION
**Pull request by damienjoldersma**

### CODE REVIEW

**Comment by cjsaylor** [comment]
:+1: This would be very useful!

**Comment by seth-reeser** [comment]
Hello, I've taken over this project. Can you please provide a use case for this? I haven't run into this need before.

**Comment by damienjoldersma** [comment]
Greetings :) My use case was basically very similar to what @tknerr originally posted in #108: basically, I have my guests hosts file managed via chef but find it necessary to manually update my host's host file (especially for doing ssl cert testing on fqdn that has to match the host and ip).  And I think I was doing something else to the hosts file that was maybe getting overwritten. Honestly, it's been a little while, and I have just gotten used to manually managing my host's host file after all, but maybe someone else would find this useful.  However, after reviewing my code, I can see that I defaulted this plugin to be disabled, so not actually using atm.  

Cheers!

**Comment by HadesArchitect** [comment]
Any updates? We also need this option. Thanks!

**Comment by jdrago999** [comment]
Ooooooooooooyyyy what's the holdup, mate??

**Comment by seth-reeser** [comment]
I have vetted this and will release within the coming days.

**Pull request merged**
